# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end
end

platform :android do
  desc "Upload to Firebase distribution"
  lane :distribute do
    build_android_app(...) # build_android_app is a built-in fastlane action.

    firebase_app_distribution(
        app: "1:668411328030:android:ed2ee43398e8b56b",
        groups: "rw-internal",
        release_notes_file: "/release-notes.txt"
    )
  end
end
